# Generated by Django 4.2.14 on 2024-10-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_model_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='image',
            field=models.ImageField(default=1, upload_to='upload/product_images'),
            preserve_default=False,
        ),
    ]
